services:
  db:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - ${SL_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - db:/bitnami/postgresql

  pgadmin:
    depends_on:
      db:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
